first_name = input("Введите ваше имя:")
last_name = input("Введите вашу фамилию:")
age = input("Введите ваш возраст:")
city = input("Введите город проживания:")
print("")
print("Привет,", first_name, last_name, "!")
print("")
print("Ваш профиль:")
print("ваш возраст :", age, "лет")